name: Update Status JSON

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - '!data/index/status.json'
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: status-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate status + catalog
        run: |
          python3 scripts/generate_status.py
          python3 scripts/generate_catalog.py
      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/index/status.json data/index/catalog.json
            git commit -m "status: refresh data/index files"
            git push
          else
            echo "No status changes."
          fi
