name: Consolidate Feed

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *' # hourly

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build consolidated feed and indices
        run: node scripts/build-feed.js

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(feed): consolidate runs into feed and indices [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi

