name: Validate Data Layout

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'data/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Validate
        run: |
          python3 scripts/validate_data.py
